### ISSUE TITLE
clickable page numbers?

### ISSUE THREAD

**Issue by mrbrown8** [hholzgra/maposmatic#10]
An enhancement request:
The multipage PDF is obviously ideal for paper printout. There may be cases where someone wants to view the PDF, say, on a tablet (or any screen really). Given the touch nature of tablets, navigation might be easier if the page numbers were clickable or tappable. 

I was envisioning 2 places of clickability. One, on the 'page grid' page (I believe it's the 3rd page on a mapsomatic output, with the grid of pagenumbers) that someone can use to jump to any page. And, two, on the edges on the individual map pages. The pages are sorted horizontally. If someone needed to navigate vertically on a map, clicking on the top or bottom margins of the page might ease that.

One example PDF file that has clickable links is:
  https://energy.gov/sites/prod/files/Large%20Power%20Transformer%20Study%20-%20June%202012_0.pdf
On page 4, there is a Table of Contents. Each entry can be clicked on and the PDF reader should jump the view to the corresponding page.

Thank you in advance for this consideration.
Thank you very much for carrying the mapsomatic torch.

**Comment by hholzgra** [comment]
That's a very good idea ...

... unfortunately the current version of Cairo Graphics does not have support for adding hyperlinks yet. 

Support for that has been added to the upcoming Cairo 1.15 release series, but so far there are only snapshot releases of that and no official stable releases.

**Comment by mrbrown8** [comment]
No worries! Thanks for the consideration.

**Comment by hholzgra** [comment]
Ubuntu now comes with a Cario Graphics version that has support for PDF links, but the pycairo version is still to old for it as of yet (has pycairo 1.16.2, needs 1.18)

**Comment by hholzgra** [comment]
Found a workaround, page edge arrows are linked to their target pages now.

Still missing: 

* links from the overview pages grid to detail pages
* links from index entries to actual map pages

**Comment by hholzgra** [comment]
See e.g. https://print.get-map.org/results//040800_2018-12-01_23-41_sylt-pdf-link-test.pdf for a map with working links

**Comment by hholzgra** [comment]
New showstopper: index lines are rendered with Pango, not with CairoGraphics directly, and on that layer PDF Hyperlink support is still missing:

https://gitlab.gnome.org/GNOME/pango/issues/290

**Comment by hholzgra** [comment]
"links from the overview pages grid to detail pages" now added by putting a transparent rectangle over the page number and having that being linked

**Comment by mrbrown8** [comment]
I saw that Cairo 1.16 was just released. I looked at your test PDF and it looks encouraging. Thank you for carrying on this request.

**Comment by hholzgra** [comment]
I created a new issue for the missing clickable index entries, so I'm closing this one as the original request has long been fulfilled.
