### ISSUE TITLE
Tippfehler "Radfar" statt _

### ISSUE THREAD

**Issue by chatelao** [hholzgra/maposmatic#115]
Winziger Typo in einem Drop-Down

Sonst vielen, vielen Dank für die grossartige Plattform.

**Comment by chatelao** [comment]
Winziger Typo in einem Drop-Down

Sonst vielen, vielen Dank für die grossartige Plattform.

**Comment by hholzgra** [comment]
Hach, wenn mal alles so einfach zu beheben wäre :)
