### ISSUE TITLE
Cookie notice doesn't go away

### ISSUE THREAD

**Issue by jidanni** [hholzgra/maposmatic#130]
On https://print.get-map.org/about/ I click 'accept cookies' but the
notice doesn't go away.

I tried to email you about it, but
```
<hartmut@php.net>: host php-smtp4-ip4.php.net[45.112.84.5] said: 550 5.7.1
    Looks like spam to me. (in reply to end of DATA command)
```

**Comment by hholzgra** [comment]
What browser are you using and what plugins / addons do you have installed?

There was a similar issue with the Ghostery addon recently:

https://github.com/hholzgra/maposmatic-vagrant/issues/64

So I assume you are hitting a similar issue ...

**Comment by jidanni** [comment]
Visit your site with
Google Chrome	125.0.6422.19 (Official Build) beta (64-bit) 
click Accept and tell me if the screen changes at all.

**Comment by hholzgra** [comment]
Ok, should be fixed now
