### ISSUE TITLE
Border and leader line on index are too thick

### ISSUE THREAD

**Issue by iriman** [hholzgra/maposmatic#20]
![2](https://user-images.githubusercontent.com/8467903/38262956-e4477ece-3783-11e8-8077-09bdcaad4b39.PNG)

Above screenshot is from this map https://maposmatic.osm-baustelle.de/maps/17134
border is very thick and covered some parts of text. Also the leader line is too thick.

![1](https://user-images.githubusercontent.com/8467903/38262938-dd7399ac-3783-11e8-9aa5-8b5489f604c3.PNG)

This is from another map https://maposmatic.osm-baustelle.de/maps/17135
Less thick but better to be thinner.

**Comment by hholzgra** [comment]
On 03.04.2018 18:53, Iman wrote:

> border is very thick and covered some parts of text. 

this part I have figured out now, all borders were supposed to be the 
same size, and aligned, but as I was clipping the rendering area for
the actual map, and was drawing the map frame while the clipping was
still active, only the inner half of the map frame was actually 
rendered, not the outer half of the line.

this is now fixed, and all border lines (title, map, index) are now
all just 1pt wide

  > Also the leader line is too thick.

this part I still need to figure out, the index generating code
is an area of the original code I haven't looked into that much
yet ...

-- 
hartmut

**Comment by hholzgra** [comment]
I also fixed the oversized dots on the dotted lines now.

The text still runs into the border line when very small fonts are used, an extra padding area is needed there as the stroke width of the frame is not taken into account yet.

The index category header bars may be suffering from the same problem at small font sizes ...

**Comment by iriman** [comment]
Thanks for solving this. Also font rendering is fine.
Yet, the first column needs a little improvement for very small fonts.
That column is too close to the right border and some part of first characters went behind the border.
![capture](https://user-images.githubusercontent.com/8467903/39958714-01492b9c-561c-11e8-8a63-dd9ddddbffff.PNG)

**Comment by hholzgra** [comment]
Now added an extra Pt between the index frame and content on all sides, so that it does not run into the frame for right-to-left text anymore.
