### ISSUE TITLE
Better style preview

### ISSUE THREAD

**Issue by ZorGleH** [hholzgra/maposmatic#25]
Hi,

This project is really awesome!
The preview of the style is a little small. It would be great to have bigger style preview picture.
For example, a 2000px x 1665px (A format) would be much more helpful when choosing your map style.
I can help in doing that if you tell me the better way to do it.
Even better would be to have the real preview of the selected area… but maybe this is another issue.

**Comment by hholzgra** [comment]
I didn't make them that large, but have now added 1.5x and 2x resolution alternatives, with the 2x being 1000x707.

Real preview is not possible as the render times are just too long for that ...
