### ISSUE TITLE
grid overlay

### ISSUE THREAD

**Issue by jasonblewis** [hholzgra/maposmatic#31]
Would it be possible to have a way of adding grid overlays?

For example in Australia we use a grid system called GDA94. It would be great if we could print maps with that grid on them

**Comment by hholzgra** [comment]
This is actually a feature for the ocitysmap renderer side of the project, not the web frontend.

I'm right now working on adding UTM grids, once that's done I'll see into adding other projections, too.

So I created a new issue on the renderer project, and will close this one here.

https://github.com/hholzgra/ocitysmap/issues/23
