### ISSUE TITLE
Japanese Label notation

### ISSUE THREAD

**Issue by KMR-zoar** [hholzgra/maposmatic#36]
Thank you developers for maintaining and developing the marvelous fork!

The Japanese label for language selection in the Navbar and map language selection is incorrect.

The notation for Japanese language is "日本語".
"日本人" is the Human of Japan ;-)

**Comment by hholzgra** [comment]
I merged the pull request, but as there are a few other changes pending in the site branch that I have to give some more testing before pushing live it may take until the weekend before the change actually shows up on the public website.

**Comment by KMR-zoar** [comment]
Thanks! I got it.
