### ISSUE TITLE
Add predefined paper size "Postcards (A6)"

### ISSUE THREAD

**Issue by sfkeller** [hholzgra/maposmatic#47]
Add predefined paper size "Post card (A6)". The most common format for postcards is DIN A6 with a size of 10.5 cm x 14.8 cm.

This is a bit related to #3 - but easier to implement.

Postcards are very popular. So what to say more? A nice example to use poscards has been recently implemented as a web app "Send me a Postcard!" here https://osmcards.org/ .

**Comment by sfkeller** [comment]
@hholzgra Hallo Hartmut: Is it a big amount of work to add another predefined paper size, like A6 for postcards?

**Comment by hholzgra** [comment]
A6 is now the smallest format offered
