### ISSUE TITLE
Crash when looking for a city

### ISSUE THREAD

**Issue by ivoire** [hholzgra/maposmatic#50]
Hello,

I get a crash when looking for the city called "Saint Pierre d'Entremont Savoie". I guess this is due to the ' in the name.

I'm getting a 500 on this query:
https://maposmatic.osm-baustelle.de/apis/nominatim/?q=saint pierre d'entremont

While nominatim is able to answer to this query
https://nominatim.openstreetmap.org/ui/search.html?city=Saint+pierre+d%27entremont&county=savoie

I guess that's because ' was not urlescaped?

**Comment by hholzgra** [comment]
should finally be fixed now
