### ISSUE TITLE
Sea marks layer as overlay

### ISSUE THREAD

**Issue by hamlet** [hholzgra/maposmatic#62]
Hi.

Would you consider adding an overlay based on the ["Sea Marks" layer](https://wiki.openseamap.org/wiki/h:En:OpenSeaMap_in_Website) from [OpenSeaMap](https://wiki.openstreetmap.org/wiki/OpenSeaMap) ?

Regards.

**Comment by hholzgra** [comment]
I'm getting requests for OpenSeaMap support quite often.

Unfortunately OpenSeaMap is using a totally different render solution than the Mapnik render library used to create standard OpenStreetMap tiles, and also the maps produced by this service.

So there's no easy way to get OpenSeaMap styles / layers integrated into the MapOSMatic software stack. I could try to just render their bitmap tiles as an overlay, but that would probably not look too well as I'd have no way to match the bitmap resolution of that tiles with the resolution and scale I'm actually rendering for.

Also trying to re-create the Sea Marks layer as a Mapnik style won't be easy as Mapnik does not support custom circle arc symbols as needed for beacon light visibility symbols ...

**Comment by hamlet** [comment]
> So there's no easy way to get OpenSeaMap styles / layers integrated into the MapOSMatic software stack. I could try to just render their bitmap tiles as an overlay, but that would probably not look too well as I'd have no way to match the bitmap resolution of that tiles with the resolution and scale I'm actually rendering for.

I thought it would as simple as overlaying tiles layers in slippy maps like Leaflet. I'm naive. ;-) 

> Also trying to re-create the Sea Marks layer as a Mapnik style won't be easy as Mapnik does not support custom circle arc symbols as needed for beacon light visibility symbols ...

I'm not sure the beacon light visibility symbols are the most useful of the layer, but anyway it would be a significant work to adapt I guess.

Thanks for your complete answer.

Best regards.
