### ISSUE TITLE
Ampersands in email notice

### ISSUE THREAD

**Issue by jidanni** [hholzgra/maposmatic#71]
Got an email:
```
your map rendering request for

  Dan&#39;s map

has successfully been processed now, and the results can be downloaded
from the rendering jobs detail pages:

  http://print.get-map.org/maps/197936
```
Are you sure you want that ampersand to show?
It's should just use the raw character.

**Comment by hholzgra** [comment]
Fixed by https://github.com/hholzgra/maposmatic/commit/15d1f310503b7cda261479f55d3d1f9b251f8150
