### ISSUE TITLE
NULL value in render job maptitle column breaks renderer and job display

### ISSUE THREAD

**Issue by hholzgra** [hholzgra/maposmatic#75]
Not sure how this could happen in the first place, but somehow a web request entry with a NULL value instead of an empty string in the maposmatic_maprenderingjob.maptitle column.

This broke both the rendering daemon process and the list and detail views in the web frontend.

**Comment by hholzgra** [comment]
Turns out I missed a step in applying the change, and then ran into yet another problem when actually doing so. Both are fixed now though and the render daemon is finally catching up.

Next task: figure out why admin email alerts can't get sent anymore ...

**Comment by AlertSubject** [comment]
Thanks for your work :)
