### ISSUE TITLE
File name uppercase/lowercase conflict

### ISSUE THREAD

**Issue by LaoshuBaby** [hholzgra/maposmatic#81]
There are 3 pair of file that only difference in case so git default see them as one file.

And every time you discord those 3 changes, git will rewrite current one with another one. We shouldn't except for `ignorecase = false`

![图片](https://user-images.githubusercontent.com/42690037/160326444-d19e614f-3ec8-4202-909c-93d463c4e106.png)

There are:

* `www/static/img/style/OpenRiverBootMap.jpg`
* `www/static/img/style/PisteMap.jpg`
* `www/static/img/overlay/MaxspeedOverlay.jpg`

**Comment by hholzgra** [comment]
Thanks for spotting, should be fixed now
